module SimpleDirectionsSpec where 
import SimpleDirections
import Test.Hspec

spec = do
  describe "Simple directions reversal" $ do
    it "Basic tests" $ do
      solve ["Begin on 3rd Blvd", "Right on First Road", "Left on 9th Dr"] `shouldBe` ["Begin on 9th Dr", "Right on First Road", "Left on 3rd Blvd"]
      solve ["Begin on Road A","Right on Road B","Right on Road C","Left on Road D"] `shouldBe` ["Begin on Road D", "Right on Road C", "Left on Road B", "Left on Road A"]
      solve ["Begin on Road A"] `shouldBe` ["Begin on Road A"]
      solve ["Begin on Fourth Crescent","Right on First Pkwy","Right on Third Avenue","Left on 3rd Boulevard","Left on Fourth Parkway","Left on Red Freeway","Left on 25th Way","Right on Seventh Grove","Right on String Close","Right on Tenth Ln","Left on 3rd Expressway","Left on 6th Drive","Left on 2nd Rd","Left on Javascript Freeway","Right on Eighth Lane"] `shouldBe` ["Begin on Eighth Lane","Left on Javascript Freeway","Right on 2nd Rd","Right on 6th Drive","Right on 3rd Expressway","Right on Tenth Ln","Left on String Close","Left on Seventh Grove","Left on 25th Way","Right on Red Freeway","Right on Fourth Parkway","Right on 3rd Boulevard","Right on Third Avenue","Left on First Pkwy","Left on Fourth Crescent"]
      solve ["Begin on Haskell Parkway","Right on Haskell Freeway","Left on 2nd Blvd","Left on 25th Street","Right on 8th Court","Right on 9th Crescent","Right on Javascript Freeway","Left on Ninth Street","Right on Red Avenue","Right on 2nd St","Right on 6th Road","Right on 9th Parkway","Right on 2nd Lane","Left on 2nd Lane","Left on Ninth Expressway","Left on Third Court","Left on Haskell Road","Right on Nim Way","Right on Pyth Crescent","Left on 9th Court","Right on Ninth Drive","Right on 5th Pkwy","Right on Javascript Ln","Right on Ninth Court","Left on 2nd Road","Left on 5th Dr","Right on Pyth Cr","Left on 2nd Pkwy","Right on Ruby Cr","Right on Nim Ln","Right on Fifth Alley","Left on Nim Avenue","Right on First Dr","Right on Sixth Backroad","Right on Seventh Dr","Right on String St","Left on Third Way","Left on Numbers Place","Right on Ruby Ln","Left on Nim Way","Left on Haskell Dr"] `shouldBe` ["Begin on Haskell Dr","Right on Nim Way","Right on Ruby Ln","Left on Numbers Place","Right on Third Way","Right on String St","Left on Seventh Dr","Left on Sixth Backroad","Left on First Dr","Left on Nim Avenue","Right on Fifth Alley","Left on Nim Ln","Left on Ruby Cr","Left on 2nd Pkwy","Right on Pyth Cr","Left on 5th Dr","Right on 2nd Road","Right on Ninth Court","Left on Javascript Ln","Left on 5th Pkwy","Left on Ninth Drive","Left on 9th Court","Right on Pyth Crescent","Left on Nim Way","Left on Haskell Road","Right on Third Court","Right on Ninth Expressway","Right on 2nd Lane","Right on 2nd Lane","Left on 9th Parkway","Left on 6th Road","Left on 2nd St","Left on Red Avenue","Left on Ninth Street","Right on Javascript Freeway","Left on 9th Crescent","Left on 8th Court","Left on 25th Street","Right on 2nd Blvd","Right on Haskell Freeway","Left on Haskell Parkway"]
      solve ["Begin on Pyth Dr","Right on Fourth Ln"] `shouldBe` ["Begin on Fourth Ln","Left on Pyth Dr"]
