name:                haskell-katas
version:             0.1.0.0
github:              "borisskert/haskell-katas"
license:             BSD3
author:              "Boris Skert"
maintainer:          "boris.skert@gmail.com"
copyright:           "2021 Boris Skert"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/borisskert/haskell-katas#readme>

dependencies:
- base >= 4.7 && < 5
- split == 0.2.5
- regex-posix == 0.96.*
- time == 1.12.*
- integer-logarithms == 1.0.4.*
- text == 2.1.1.*
- containers == 0.6.8.*
- array == 0.5.8.*
- filepath == 1.4.301.*
- parsec == 3.1.17.*
- megaparsec == 9.6.*

library:
  source-dirs: src

tests:
  haskell-katas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-katas
    - hspec == 2.11.*
    - hspec-core == 2.11.*
    - QuickCheck == 2.14.3
    - HUnit == 1.6.2.0
    - haskell-src-exts == 1.23.*
    - async == 2.2.*
    - vector == 0.13.2.*
