module Test.CodeWars.OCRMistakesSpec where

import CodeWars.OCRMistakes (correct)
import Test.Hspec

spec :: Spec
spec = do
  describe "correct" $ do
    it "should work for some examples" $ do
      correct "1F-RUDYARD K1PL1NG" `shouldBe` "IF-RUDYARD KIPLING"
      correct "R0BERT MERLE - THE DAY 0F THE D0LPH1N" `shouldBe` "ROBERT MERLE - THE DAY OF THE DOLPHIN"
      correct "R1CHARD P. FEYNMAN - THE FEYNMAN LECTURE5 0N PHY51C5" `shouldBe` "RICHARD P. FEYNMAN - THE FEYNMAN LECTURES ON PHYSICS"
      correct "R1CHARD P. FEYNMAN - 5TAT15T1CAL MECHAN1C5" `shouldBe` "RICHARD P. FEYNMAN - STATISTICAL MECHANICS"
      correct "5TEPHEN HAWK1NG - A BR1EF H15T0RY 0F T1ME" `shouldBe` "STEPHEN HAWKING - A BRIEF HISTORY OF TIME"
      correct "5TEPHEN HAWK1NG - THE UN1VER5E 1N A NUT5HELL" `shouldBe` "STEPHEN HAWKING - THE UNIVERSE IN A NUTSHELL"
      correct "ERNE5T HEM1NGWAY - A FARWELL T0 ARM5" `shouldBe` "ERNEST HEMINGWAY - A FARWELL TO ARMS"
      correct "ERNE5T HEM1NGWAY - F0R WH0M THE BELL T0LL5" `shouldBe` "ERNEST HEMINGWAY - FOR WHOM THE BELL TOLLS"
      correct "ERNE5T HEM1NGWAY - THE 0LD MAN AND THE 5EA" `shouldBe` "ERNEST HEMINGWAY - THE OLD MAN AND THE SEA"
      correct "J. R. R. T0LK1EN - THE L0RD 0F THE R1NG5" `shouldBe` "J. R. R. TOLKIEN - THE LORD OF THE RINGS"
      correct "J. D. 5AL1NGER - THE CATCHER 1N THE RYE" `shouldBe` "J. D. SALINGER - THE CATCHER IN THE RYE"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE PH1L050PHER'5 5T0NE" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE PHILOSOPHER'S STONE"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE CHAMBER 0F 5ECRET5" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE CHAMBER OF SECRETS"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE PR150NER 0F Azkaban" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE PRISONER OF Azkaban"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE G0BLET 0F F1RE" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE GOBLET OF FIRE"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE 0RDER 0F PH0EN1X" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE ORDER OF PHOENIX"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE HALF-BL00D PR1NCE" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE HALF-BLOOD PRINCE"
      correct "J. K. R0WL1NG - HARRY P0TTER AND THE DEATHLY HALL0W5" `shouldBe` "J. K. ROWLING - HARRY POTTER AND THE DEATHLY HALLOWS"
      correct "UR5ULA K. LE GU1N - A W1ZARD 0F EARTH5EA" `shouldBe` "URSULA K. LE GUIN - A WIZARD OF EARTHSEA"
      correct "UR5ULA K. LE GU1N - THE T0MB5 0F ATUAN" `shouldBe` "URSULA K. LE GUIN - THE TOMBS OF ATUAN"
      correct "UR5ULA K. LE GU1N - THE FARTHE5T 5H0RE" `shouldBe` "URSULA K. LE GUIN - THE FARTHEST SHORE"
      correct "UR5ULA K. LE GU1N - TALE5 FR0M EARTH5EA" `shouldBe` "URSULA K. LE GUIN - TALES FROM EARTHSEA"
