---
name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run stack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell environment
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.6.5'
          cabal-version: '2.4.0.1'
          enable-stack: true
          stack-version: '2.7.1'

      - name: Setup stack cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack

      - name: Build solution
        run: stack build

      - name: Run tests
        run: stack test
